### ISSUE TITLE
[Suggestion]: Serverside Plugin

### ISSUE THREAD

**Issue by Ar41GG** [Fuzss/forgeconfigapiport#23]
### Suggestion (Required)

Is that possible to do plugin, like PlasmoVoice, Emotecraft, to support mod on vanilla servers?

**Comment by Fuzss** [comment]
Why should the mod be supported on vanilla servers?

**Comment by Fuzss** [comment]
Closing this now. If this is still important to you, please state a more detailed description to why this is necessary (like a proper use case).
