### ISSUE TITLE
[Bug]: Users without this mod can't join LAN worlds created by a user with this mod

### ISSUE THREAD

**Issue by DarkFireNinja** [Fuzss/forgeconfigapiport#27]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.6

### Notes (Required)

I know that this bug has already been reported, but this has not yet been fixed, and it has been almost 3 months since the issue has been reported. So i am making this Issue because i'm not sure if you forgot about this or not cause you haven't given any feedback on if you're still trying to fix this bug. Anyways this is the error that my family members get when they try to join my LAN world: Packet 0/15 was larger than I expected. (By the way i am the only one using the mod, my family members are not.) So can you please fix this bug so that i can use mods like Legendary Tooltips and Puzzles Lib (which is a requirement for the Better Animations Collection Mod) while playing in a LAN world with my family members.

Thanks alot.

**Comment by Fuzss** [comment]
Hi! Just letting you know that I have this issue on my radar, but have not found a fix for it. I'll let you know when there's some progress. For now I can only recommend uninstalling the mod and the ones that depend on it, or for the other players to also move to a modded mc instance.

**Comment by DarkFireNinja** [comment]
Thank you very much for the response and i'm glad to know that you are
still working on this issue. I am sorry if i bothered you, i just wanted to
make sure that the bug was still being worked on because it is very
important for me to be able to play on LAN servers using some client side
mods which depended on this mod. Anyways good luck on your amazing work,
Your mods are awesome.

Thanks again.

**Comment by Fuzss** [comment]
So in v5.0.0 (1.19.3 only for now) I finally added a workaround for this issue: There is a new config file `.minecraft/config/forgeconfigapiport.toml`.

When you want to play on LAN using a modded instance with Forge Config Api Port as host, disable the config command in this file (requires a game restart). This will prevent the problematic command serializers from being sent to connecting vanilla clients.

As the option suggests, the `/config` command is completely disabled by that, but honestly I'd much rather recommend the Configured mod over using the command anyways.

Please tell me if everything works correctly now when you update to 1.19.3! I'll close the issue now as I'm pretty sure that's all that was to it, but you can never be sure haha.

**Comment by DarkFireNinja** [comment]
Hey, Thanks a lot for all of your work. I think that i will wait a bit longer until it releases for 1.19.2 because most of the mods that i want to use -that depend on Forge Config API Port- aren't even for 1.19.3 anyway, so i will have to either wait for this mod to be for 1.19.2 or i will wait for the other mods to update to 1.19.3. Anyways thanks a lot for all of your work!

**Comment by DJtheRedstoner** [comment]
Given that the command is only registered on the client side, why not just use fabric's client side command api? This could be a bit tricky since the common module doesn't have fabric api in it, but it should still be possible to do this in a way that is far more elegant than the config option.

**Comment by Fuzss** [comment]
That's awesome, didn't even think of this. Thank you so much!

**Comment by DarkFireNinja** [comment]
Hey Fuzss, i don't want to annoy you are anything like that, but because DJtheRedstoner gave you a new way of fixing this issue, will you be able to make this work for 1.19.2 in the future. Thanks!

**Comment by Fuzss** [comment]
@DarkFireNinja Done!

**Comment by DarkFireNinja** [comment]
Thank you so much i really appreciate it!
