### ISSUE TITLE
[Suggestion]: Allow disabling serverconfigs globally

### ISSUE THREAD

**Issue by Dekamir** [Fuzss/forgeconfigapiport#32]
### Suggestion (Required)

To prevent mods from creating their **config** files in the **world's** directory, instead of the **named-standard** **/config** directory, there may be a config for FCAPIP to force all mods to use /config instead of /world/serverconfig.

**Comment by Fuzss** [comment]
Implemented in v5.0.0 (1.19.3 only for now), enabled by default as I've wanted to do this for a long time with all the user confusion bothering me for a long time.
