### ISSUE TITLE
[Crash]: Game won't start in dev environment after updating from 5.0.3

### ISSUE THREAD

**Issue by thomasglasser** [Fuzss/forgeconfigapiport#37]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

5.0.7

### Notes (Required)

1. Update to 5.0.7 from 5.0.3
2. Compile fails

### Crash Report (Required)

https://gist.github.com/thomasglasser/8ecd068625b841a2229fcbb55af990f7

**Comment by Fuzss** [comment]
Add these to the dependencies block of build.gradle

implementation 'com.electronwill.night-config:core:3.6.5'
    implementation 'com.electronwill.night-config:toml:3.6.5'

**Comment by Fuzss** [comment]
They seem to not be downloaded automatically from the pom I‘m not sure why yet.

**Comment by thomasglasser** [comment]
Adding those didn't seem to do anything.

**Comment by Fuzss** [comment]
Fixed in v5.0.9.
