### ISSUE TITLE
[Crash]: Game crashing whilst this mod is installed

### ISSUE THREAD

**Issue by alfred-exe** [Fuzss/forgeconfigapiport#41]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

any of the 1.19.2 versions newer than v4.2.5

### Notes (Required)

The game crashes in a new world when you open the pause screen, and it crashes immediately when you try to load that world every time after that.

### Crash Report (Required)

https://gist.github.com/alfred-exe/4fdf32e4ade85a0f5456ead8e84ee297

### latest.log (Optional)

https://gist.github.com/alfred-exe/3a6d71a9f8bab7285f2ebd79c0c159e8

### Edit:
It seems that the reason for older versions crashing was due to changes with the newer versions which they were incompatible with, and the older versions seem to work fine. This was only tested on v4.2.5, however, which means it could be a exception.

### Edit 2:
The older version still crashes when I open my inventory in game.

**Comment by Fuzss** [comment]
Install mod menu

**Comment by Fuzss** [comment]
Or uninstall smooth swapping. This doesn‘t have anything to do with this mod.
