### ISSUE TITLE
[Suggestion]: Please update the mod to 1.20

### ISSUE THREAD

**Issue by danielniccoli** [Fuzss/forgeconfigapiport#44]
### Suggestion (Required)

Please update the mod to 1.20

**Comment by JoostMSoftware** [comment]
The mod is already updated but isn't out yet on CF/Modrinth! Should take a bit of time until that's there

**Comment by danielniccoli** [comment]
Is there a place I can download it already? Unfortunately, the owner didn't release it to GitHub releases.

**Comment by Fuzss** [comment]
Release is out on CF, Modrinth is giving me timeouts when uploading, will try again tomorrow.
