### ISSUE TITLE
[Bug]: NeoForge wrong package

### ISSUE THREAD

**Issue by GirafiStudios** [Fuzss/forgeconfigapiport#49]
### Mod Loader (Required)

NeoForge

### Minecraft Version (Required)

1.20.2

### Mod Version (Required)

9.1.1

### Notes (Required)

I see you fixed the class name for the NeoForge implementation in 9.1.1, which is great!
However the package path there is still wrong unfortunately.

It´s currently set to:
net.neoforged.common.ModConfigSpec

In NeoForge it is:
net.neoforged.neoforge.common.ModConfigSpec

**Comment by Fuzss** [comment]
Thanks, fixed in v9.1.2.
