### ISSUE TITLE
[Bug]: NeoForge Version Fails to Load

### ISSUE THREAD

**Issue by hammy275** [Fuzss/forgeconfigapiport#53]
### Mod Loader (Required)

NeoForge

### Minecraft Version (Required)

1.20.2

### Mod Version (Required)

v20.2.25

### Notes (Required)

The issue at least appears to be that due to a missing `mandatory` field in `mods.toml`, the NeoForge version (implementing Forge's API) fails to load.

1. Install latest version of Forge Config API Port for NeoForge from CurseForge/Modrinth
2. Run game under NeoForge 20.2.86 or NeoForge 20.2.88 (other versions untested)
3. Observe a log similar to the one provided here and NeoForge complaining of an invalid mod file, thus not loading the mod.

~~I need this working to test a port of my mod to NeoForge, so I may open a PR for this in a bit, since if the log is to believed, this shouldn't require much to fix.~~ Here's a PR for a fix: https://github.com/Fuzss/forgeconfigapiport/pull/54

### latest.log (Optional)

https://gist.github.com/hammy275/6c803ca740b1dff1786369a5d800bcba

**Comment by Fuzss** [comment]
Thanks for finding this, the NeoForge distribution is the only one I don't use myself so I didn't catch that. 😅
