### ISSUE TITLE
[Bug]: Neoforge 21.0.82 changes crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [Fuzss/forgeconfigapiport#59]
### Mod Loader (Required)

NeoForge

### Minecraft Version (Required)

1.21

### Mod Version (Required)

21.0.1

### Notes (Required)

https://github.com/Exopandora/ShoulderSurfing/issues/228#issuecomment-2225990782

**Comment by Fuzss** [comment]
Fixed in v21.0.2.
