### ISSUE TITLE
[Bug]: Loading, Reloading, and Unloading events registered with ForgeModConfigEvents are never called.

### ISSUE THREAD

**Issue by alejandrocoria** [Fuzss/forgeconfigapiport#60]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.21

### Mod Version (Required)

21.0.2

### Notes (Required)

Events work correctly on 21.0.1 with everything else the same.

**Comment by Fuzss** [comment]
Should be fixed in v21.0.3. Please test if this is indeed the case and reopen if any issues remain.
