### ISSUE TITLE
[Crash]: Server fails to start with newest verison

### ISSUE THREAD

**Issue by Wash113** [Fuzss/forgeconfigapiport#61]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.21

### Mod Version (Required)

v21.0.3

### Notes (Required)

Hey! Server seems to have a hard time starting with the newest version. Could be on the side of the Small Ships mod, but downgrading to v21.0.2 fixes the issue. Im going to report the issue to the Small Ships team also. There is no crash log, so Im sending the latest log as the crash log. Happy hunting!

### Crash Report (Required)

https://mclo.gs/zYuNrm0

**Comment by Fuzss** [comment]
The NeoForge config implementation has changed, and FCAP has been updated to reflect those changes.

In that particular case `ModConfig::getFullPath` throwing an exception is indeed an oversight on my end that I can fix, but even then their code is going to crash on the next call to `ModConfig::save`.

So in short they need to update their config implementation for the NeoForge changes.

**Comment by Fuzss** [comment]
I've now implemented a workaround for `ModConfig::save` in v21.0.5. Can you please test if that version works again on servers?

**Comment by Wash113** [comment]
Seems to work, thanks as always!
