### ISSUE TITLE
[Crash]: Crash when using with NeoForge 21.0.143

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Fuzss/forgeconfigapiport#63]
### Mod Loader (Required)

NeoForge

### Minecraft Version (Required)

1.21

### Mod Version (Required)

v21.0.6

### Notes (Required)

1. Install NeoForge 21.0.143.
2. Install *Forge Config API Port* and any mods that depend on it.
3. Launch the game

### Crash Report (Required)

https://gist.github.com/3gf8jv4dv/809de10d2d5a6704a3d14aeb41776321

**Comment by Fuzss** [comment]
Should be fixed in v21.0.7. Please reopen if there is still an issue.
