### ISSUE TITLE
[Suggestion]: Add `NeoForge` to the `Mod Loader` option when submitting bug/crash reports

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Fuzss/forgeconfigapiport#64]
### Suggestion (Required)

Sorry, but when I submitted a crash report, I found that there was no `NeoForge` option. This caused me to manually modify the issue description after submitting the issue.

I checked several mods you recently updated, and their issue templates all have the `NeoForge` option.

**Comment by Fuzss** [comment]
Thanks!
