### ISSUE TITLE
[Bug]: 1.21 fabric build contains mods.toml

### ISSUE THREAD

**Issue by Exopandora** [Fuzss/forgeconfigapiport#66]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.8

### Minimal Setup (Required)

Yes

### Notes (Required)

I noticed that the 1.21 fabric build of FCAP ships with a mods.toml, which should not be needed for a fabric mod.

### latest.log (Required)

-

**Comment by Fuzss** [comment]
Fixed for 1.21.1+.
