### ISSUE TITLE
[Bug]: Server could not be shut down normally

### ISSUE THREAD

**Issue by swe3per** [Fuzss/forgeconfigapiport#68]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.08

### Minimal Setup (Required)

Yes

### Notes (Required)

Fabric api version：fabric-api-0.102.0+1.21

[Server] [07:46:12] [Server thread/INFO]: Done (8.458s)! For help, type "help"
> stop
[Server] [07:46:16] [Server thread/INFO]: Stopping the server
[Server] [07:46:16] [Server thread/INFO]: Stopping server
[Server] [07:46:16] [Server thread/INFO]: Saving players
[Server] [07:46:16] [Server thread/INFO]: Saving worlds
[Server] [07:46:16] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[Server] [07:46:17] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[Server] [07:46:17] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[Server] [07:46:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [07:46:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [07:46:17] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [07:46:17] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

### latest.log (Required)

https://paste.ee/p/ILXZm

**Comment by kennethsible** [comment]
I also encountered a similar issue (unable to shut down) after upgrading our server to 1.21. I eventually managed to isolate the issue to Forge Config API Port.

**Comment by kennethsible** [comment]
I created a new server instance and removed all mods except: Fabric API, Puzzles Lib, Forge Config API Port, Easy Anvils, Easy Magic, and Easy Shulker Boxes. I have to force kill the server every time as it just hangs on shut down

**Comment by Fuzss** [comment]
Should be fixed in v21.1.1.
