### ISSUE TITLE
[Bug]: Reference map 'forgeconfigapiport.common.refmap.json' for forgeconfigapiport.common.mixins.json could not be read.

### ISSUE THREAD

**Issue by Shadowblitz16** [Fuzss/forgeconfigapiport#69]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

21.1.1

### Minimal Setup (Required)

No

### Notes (Required)

Please fix the warning.

### latest.log (Required)

https://mclo.gs/b77W8jf

**Comment by Fuzss** [comment]
That’s not an issue.

**Comment by Shadowblitz16** [comment]
Then mute the message if it's not an issue.
