### ISSUE TITLE
[Bug]: save() does not save the file

### ISSUE THREAD

**Issue by alejandrocoria** [Fuzss/forgeconfigapiport#70]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

21.1.1

### Minimal Setup (Required)

Yes

### Notes (Required)

MapFrontiers developer here.
In both Fabric and NeoForge I can't save Forge configs in these latest versions. It gets to [this line](https://github.com/Fuzss/forgeconfigapiport/blob/37dc4e0c3182171f922728ff57fcf1ddebf6989a/1.21.1/Common-ForgeApi/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L134) and the if is false so it does nothing.

The log is not helpful, you can see the repository [here](https://github.com/alejandrocoria/MapFrontiers), ask whatever you want.

### latest.log (Required)

https://gist.github.com/alejandrocoria/6e66c35be8bf6abfa62dec53933a9baf

**Comment by Fuzss** [comment]
I just pushed v21.1.2 to the Maven, does it fix the issue for you?
Please provide some feedback, until that I'll hold off on publishing a new release to CF & Modrinth.

**Comment by alejandrocoria** [comment]
It worked, good job!
I will keep your recommendation in mind.
Thank you very much!

**Comment by Fuzss** [comment]
Great, v21.1.2 is out on CF & Modrinth now.
